### ISSUE TITLE
Does not fetch backgroup-image correctly

### ISSUE THREAD

**Issue by mlaksholm** [xunil75/Ombi-omBlur#2]
When copying the custom CSS it does not load the background-images correctly
I changed background-image: url("images/blur-noise.png"), url("images/blur-light.png");
to
  background-image: url("https://archmonger.github.io/Blackberry-Themes/Resources/blur-noise.png"), url("https://archmonger.github.io/Blackberry-Themes/Resources/blur-light.png");

and it works fine. Something I've done wrong or code-issue?

**Comment by xunil75** [comment]
I'm sorry for the very late reply. Jesus I could I miss that?? I uploaded the images. Please follow the instructions and upload the .css again.
